export const FETCH_NUMBER_OF_AIDS_REQUEST = "FETCH_NUMBER_OF_AIDS_REQUEST";
export const FETCH_NUMBER_OF_AIDS_SUCCESS = "FETCH_NUMBER_OF_AIDS_SUCCESS";
export const FETCH_NUMBER_OF_AIDS_FAILURE = "FETCH_NUMBER_OF_AIDS_FAILURE";
