export const FETCH_LOGGED_USER_DATA_REQUEST = "FETCH_LOGGED_USER_DATA_REQUEST";
export const FETCH_LOGGED_USER_DATA_SUCCESS = "FETCH_LOGGED_USER_DATA_SUCCESS";
export const FETCH_LOGGED_USER_DATA_FAILURE = "FETCH_LOGGED_USER_DATA_FAILURE";
