export const FETCH_NUMBER_OF_HELPED_AIDS_REQUEST =
	"FETCH_NUMBER_OF_HELPED_AIDS_REQUEST";
export const FETCH_NUMBER_OF_HELPED_AIDS_SUCCESS =
	"FETCH_NUMBER_OF_HELPED_AIDS_SUCCESS";
export const FETCH_NUMBER_OF_HELPED_AIDS_FAILURE =
	"FETCH_NUMBER_OF_HELPED_AIDS_FAILURE";
