export const FETCH_NUMBER_OF_USERS_REQUEST = "FETCH_NUMBER_OF_USERS_REQUEST";
export const FETCH_NUMBER_OF_USERS_SUCCESS = "FETCH_NUMBER_OF_USERS_SUCCESS";
export const FETCH_NUMBER_OF_USERS_FAILURE = "FETCH_NUMBER_OF_USERS_FAILURE";
