export const FETCH_AID_CATEGORY_REQUEST = "FETCH_AID_CATEGORY_REQUEST";
export const FETCH_AID_CATEGORY_SUCCESS = "FETCH_AID_CATEGORY_SUCCESS";
export const FETCH_AID_CATEGORY_FAILURE = "FETCH_AID_CATEGORY_FAILURE";
