export const FETCH_AID_LOCATION_REQUEST = 'FETCH_AID_LOCATION_REQUEST'
export const FETCH_AID_LOCATION_SUCCESS = 'FETCH_AID_LOCATION_SUCCESS'
export const FETCH_AID_LOCATION_FAILURE = 'FETCH_AID_LOCATION_FAILURE'