export const FETCH_DETAIL_CONTENT_REQUEST = 'FETCH_DETAIL_CONTENT_REQUEST'
export const FETCH_DETAIL_CONTENT_SUCCESS = 'FETCH_DETAIL_CONTENT_SUCCESS'
export const FETCH_DETAIL_CONTENT_FAILURE = 'FETCH_DETAIL_CONTENT_FAILURE'