export const FETCH_MAP_SEARCH_AID_REQUEST = "FETCH_MAP_SEARCH_AID_REQUEST";
export const FETCH_MAP_SEARCH_AID_SUCCESS = "FETCH_MAP_SEARCH_AID_SUCCESS";
export const FETCH_MAP_SEARCH_AID_FAILURE = "FETCH_MAP_SEARCH_AID_FAILURE";
