export const FETCH_POPUP_CONTENT_REQUEST = 'FETCH_POPUP_CONTENT_REQUEST'
export const FETCH_POPUP_CONTENT_SUCCESS = 'FETCH_POPUP_CONTENT_SUCCESS'
export const FETCH_POPUP_CONTENT_FAILURE = 'FETCH_POPUP_CONTENT_FAILURE'