export const FETCH_LOGGED_USERS_PENDING_AIDS_REQUEST =
	"FETCH_LOGGED_USERS_PENDING_AIDS_REQUEST";
export const FETCH_LOGGED_USERS_PENDING_AIDS_SUCCESS =
	"FETCH_LOGGED_USERS_PENDING_AIDS_SUCCESS";
export const FETCH_LOGGED_USERS_PENDING_AIDS_FAILURE =
	"FETCH_LOGGED_USERS_PENDING_AIDS_FAILURE";
/* ******************** */
export const FETCH_LOGGED_USERS_ACTIVE_AIDS_REQUEST =
	"FETCH_LOGGED_USERS_ACTIVE_AIDS_REQUEST";
export const FETCH_LOGGED_USERS_ACTIVE_AIDS_SUCCESS =
	"FETCH_LOGGED_USERS_ACTIVE_AIDS_SUCCESS";
export const FETCH_LOGGED_USERS_ACTIVE_AIDS_FAILURE =
	"FETCH_LOGGED_USERS_ACTIVE_AIDS_FAILURE";

/* ******************** */
