export const FETCH_LOGGED_USERS_PENDING_COMMENTS_REQUEST =
	"FETCH_LOGGED_USERS_PENDING_COMMENTS_REQUEST";
export const FETCH_LOGGED_USERS_PENDING_COMMENTS_SUCCESS =
	"FETCH_LOGGED_USERS_PENDING_COMMENTS_SUCCESS";
export const FETCH_LOGGED_USERS_PENDING_COMMENTS_FAILURE =
	"FETCH_LOGGED_USERS_PENDING_COMMENTS_FAILURE";

/* ******************** */
export const FETCH_LOGGED_USERS_ACTIVE_COMMENTS_REQUEST =
	"FETCH_LOGGED_USERS_ACTIVE_COMMENTS_REQUEST";
export const FETCH_LOGGED_USERS_ACTIVE_COMMENTS_SUCCESS =
	"FETCH_LOGGED_USERS_ACTIVE_COMMENTS_SUCCESS";
export const FETCH_LOGGED_USERS_ACTIVE_COMMENTS_FAILURE =
	"FETCH_LOGGED_USERS_ACTIVE_COMMENTS_FAILURE";
