export const FETCH_PENDING_COMMENTS_REQUEST = "FETCH_PENDING_COMMENTS_REQUEST";
export const FETCH_PENDING_COMMENTS_SUCCESS = "FETCH_PENDING_COMMENTS_SUCCESS";
export const FETCH_PENDING_COMMENTS_FAILURE = "FETCH_PENDING_COMMENTS_FAILURE";
