export const FETCH_PENDING_USERS_REQUEST = "FETCH_PENDING_USERS_REQUEST";
export const FETCH_PENDING_USERS_SUCCESS = "FETCH_PENDING_USERS_SUCCESS";
export const FETCH_PENDING_USERS_FAILURE = "FETCH_PENDING_USERS_FAILURE";
