export const FETCH_PENDING_AIDS_REQUEST = "FETCH_PENDING_AIDS_REQUEST";
export const FETCH_PENDING_AIDS_SUCCESS = "FETCH_PENDING_AIDS_SUCCESS";
export const FETCH_PENDING_AIDS_FAILURE = "FETCH_PENDING_AIDS_FAILURE";
